services:
  database:
    image: mysql:9.7
    container_name: mysql-db
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - database:/var/lib/mysql

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ=America/La_Paz
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - "${NODE_PORT}:${NODE_PORT}"

  web-app:
    build:
      context: ../Deshidratador-Front
      dockerfile: Dockerfile
      target: runner
    container_name: web-app
    restart: always
    environment:
      - TZ=America/La_Paz
    depends_on:
      - node-app
      - database
    ports:
      - "80:80"

volumes:
  database:

networks:
  deshidratador_net:
    driver: bridge
